### PR TITLE
Configs for IconicUni font

### PR DESCRIPTION
**Pull request by puzrin**
1. Joined IconicFill + IconicStroke
2. Fixed symbols code, where possible, to new one from unicode 6.1 standard
3. Conflicting codes (after merge & remap) resolved by addind +0x80 to `Stroke` chars. That changed only few chars in PUA.

### CODE REVIEW

**Comment by puzrin** [comment]
Sorry for wrong name in commit lines. All internals are correct. I'm trying to improve several OFL fonts, and had to sleep a bit more :) .

**Comment by somerandomdude** [comment]
Ah, I see - so a separate font face that merges all of the icons into one font. I'm still conflicted on the mapping structure for duplicate icons (with different styles). I wrote about the subject here: http://somerandomdude.com/2012/01/31/font-embedding-icons-the-right-way/. Having one document icon map to the Unicode document glyph and another map to an unused glyph seems semantically inappropriate.  

I would prefer to have this unified font exist in a fork. I think a unified font is useful, but I strongly support proper Unicode mapping when possible. To me, this seems akin to putting regular and bold weights of the letter 'a' in one font where the regular weight was mapped to 'a' and the other was mapped to a character in the private range.

**Comment by puzrin** [comment]
1. Imho, semantic criteria is not appliable here. If we are speaking about bold/italic - all font symbols differs. In your case, only a small count. It's more "different symbols", than "different style". I think, the proper way is just to request adding new glyphs to unicode standard. And it's a normal pracrtice to add "not existing" symbols in PUA until that happens.
2. In practice, it's more convenient (for users) to have all icons in one file too.
3. Thechnically, i can maintain separate repo. But design is not my business, and i'd prefer to return results in upstream. I don't ask to remove Stroke/Fill. Just to add third variand. It will not cost you anything. Iconnic font files still have some bugs, and it's much more easy to fix those in single place.

**Comment by somerandomdude** [comment]
OK, let's give this a shot and see what people think. Thanks again for all the help.

**Pull request merged**
